[package]
name = "mini_sbc"
version = "0.1.3"
edition = "2021"
description = "Bluetooth audio SBC decoder"
keywords = ["audio", "SBC", "decode"]
repository = "https://github.com/823984418/mini_sbc"
license = "MIT OR Apache-2.0"

[dependencies]

